language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PACKAGE="arp"
  matrix:
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.03 EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git" DEPOPTS="lwt tcpip mirage-types-lwt duration" TESTS=false
    - OCAML_VERSION=4.04 EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git" DEPOPTS="lwt tcpip mirage-types-lwt duration" TESTS=false
notifications:
  email: false
