language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
sudo: false
services:
  - docker
env:
  global:
    - PINS="arp:. arp-mirage:."
    - DISTRO=alpine
    - TESTS=true
    - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
    - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -uy"
  matrix:
    - OCAML_VERSION=4.04 PACKAGE="arp-mirage"
    - OCAML_VERSION=4.05 PACKAGE="arp"
    - OCAML_VERSION=4.06 PACKAGE="arp-mirage"
    - OCAML_VERSION=4.07 PACKAGE="arp"
    - OCAML_VERSION=4.08 PACKAGE="arp" DEPOPTS="arp-mirage"
notifications:
  email: false
