language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PACKAGE="arp"
  matrix:
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.03 EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git" DEPOPTS="lwt tcpip duration mirage-protocols-lwt mirage-time-lwt mirage-clock mirage-protocols" TESTS=false
    - OCAML_VERSION=4.04 EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git" DEPOPTS="lwt tcpip duration mirage-protocols-lwt mirage-time-lwt mirage-clock mirage-protocols" TESTS=false
notifications:
  email: false
