language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  - PACKAGE="arp" OCAML_VERSION=4.02
  - PACKAGE="arp" OCAML_VERSION=4.03
  - PACKAGE="arp" OCAML_VERSION=4.02 EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git" DEPOPTS="lwt tcpip mirage-types duration" TESTS=false
  - PACKAGE="arp" OCAML_VERSION=4.03 EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git" DEPOPTS="lwt tcpip mirage-types duration" TESTS=false
notifications:
  email: false
